# Template de Secrets - NUNCA commitar com valores reais
# Use variáveis de ambiente ou vault em produção

version: "1.0"

# Configuração de fonte de secrets
secrets_backend:
  type: "${SECRETS_BACKEND:-env}" # env, vault, k8s
  vault:
    address: "${VAULT_ADDR}"
    token: "${VAULT_TOKEN}"
    path: "secret/mcp-ultra"

# Mapeamento de secrets (usar placeholders)
database:
  host: "${DB_HOST:-localhost}"
  port: "${DB_PORT:-5432}"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_NAME}"
  ssl_mode: "${DB_SSL_MODE:-require}"

nats:
  url: "${NATS_URL:-nats://localhost:4222}"
  username: "${NATS_USERNAME}"
  password: "${NATS_PASSWORD}"
  token: "${NATS_TOKEN}"

telemetry:
  otlp:
    endpoint: "${OTLP_ENDPOINT:-localhost:4317}"
    headers:
      authorization: "${OTLP_AUTH_TOKEN}"
  
prometheus:
    username: "${PROMETHEUS_USERNAME}"
    password: "${PROMETHEUS_PASSWORD}"

auth:
  jwt_secret: "${JWT_SECRET}"
  api_keys: "${API_KEYS}" # JSON array

encryption:
  master_key: "${ENCRYPTION_MASTER_KEY}"
  key_rotation_days: 90

# Validação de secrets obrigatórios
required_secrets:
  - DB_PASSWORD
  - NATS_TOKEN
  - JWT_SECRET
  - ENCRYPTION_MASTER_KEY

# Secrets opcionais com defaults seguros
optional_secrets:
  OTLP_AUTH_TOKEN: ""
  PROMETHEUS_USERNAME: "prometheus"
