apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: mcp-model-ultra
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mcp-model-ultra
  service:
    port: 80
  analysis:
    interval: 1m
    threshold: 10
    stepWeight: 5
    maxWeight: 50
    metrics:
      - name: request-success-rate
        thresholdRange:
          min: 99
        interval: 1m
      - name: request-duration
        thresholdRange:
          max: 500
        interval: 1m
