name: ci
on:
  push: { branches: ["main"] }
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: "1.22.x" }
      - name: Install tools
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.60.3
          echo "$HOME/bin" >> $GITHUB_PATH
      - name: Make CI
        run: make ci
      - name: HTML coverage artifact
        if: always()
        run: make coverhtml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-html
          path: coverage.html
