# GoSec Security Scanner
# Static analysis for Go code security issues

name: GoSec

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main"]
  schedule:
    # Run every Monday at 7 AM UTC
    - cron: "0 7 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  gosec:
    name: GoSec Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
          cache: true

      - name: Install GoSec
        run: go install github.com/securego/gosec/v2/cmd/gosec@v2.21.4

      - name: Run GoSec Security Scanner
        run: |
          $(go env GOPATH)/bin/gosec \
            -no-fail \
            -fmt sarif \
            -out results.sarif \
            -exclude-dir=vendor \
            -exclude-dir=test \
            -exclude-dir=mocks \
            -severity medium \
            ./...
        continue-on-error: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: results.sarif
          category: gosec

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: gosec-results
          path: results.sarif
          retention-days: 30
