name: lint-and-test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/golang/mock/mockgen@latest

      - name: Lint
        run: golangci-lint run --timeout=5m

      - name: Test
        run: go test ./... -count=1 -coverprofile=coverage.out

      - name: Coverage HTML
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage.html